#ifndef HTML_FORMS_H
#define HTML_FORMS_H

const char* HTML_CONFIG_FORM = 
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "<title>Configuración WiFi</title>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<style>"
    "body { "
    "    font-family: Arial, sans-serif; "
    "    margin: 0; "
    "    padding: 20px; "
    "    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
    "    min-height: 100vh;"
    "    display: flex;"
    "    justify-content: center;"
    "    align-items: center;"
    "}"
    ".container { "
    "    background: white; "
    "    padding: 30px; "
    "    border-radius: 15px; "
    "    box-shadow: 0 10px 30px rgba(0,0,0,0.2);"
    "    max-width: 400px;"
    "    width: 100%;"
    "}"
    "h2 { "
    "    text-align: center; "
    "    color: #333; "
    "    margin-bottom: 25px;"
    "    font-size: 24px;"
    "}"
    ".form-group { "
    "    margin-bottom: 20px; "
    "}"
    "label { "
    "    display: block; "
    "    margin-bottom: 8px; "
    "    font-weight: bold; "
    "    color: #555; "
    "}"
    "input[type='text'], "
    "input[type='password'], "
    "input[type='number'] { "
    "    width: 100%; "
    "    padding: 12px 15px; "
    "    border: 2px solid #ddd; "
    "    border-radius: 8px; "
    "    font-size: 16px; "
    "    box-sizing: border-box; "
    "    transition: border-color 0.3s; "
    "}"
    "input[type='text']:focus, "
    "input[type='password']:focus, "
    "input[type='number']:focus { "
    "    border-color: #667eea; "
    "    outline: none; "
    "}"
    ".checkbox-group { "
    "    display: flex; "
    "    align-items: center; "
    "    margin: 20px 0; "
    "}"
    ".checkbox-group input[type='checkbox'] { "
    "    margin-right: 10px; "
    "    transform: scale(1.2); "
    "}"
    ".btn { "
    "    width: 100%; "
    "    padding: 14px; "
    "    border: none; "
    "    border-radius: 8px; "
    "    font-size: 16px; "
    "    font-weight: bold; "
    "    cursor: pointer; "
    "    transition: background-color 0.3s; "
    "    margin-bottom: 10px; "
    "}"
    ".btn-primary { "
    "    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
    "    color: white; "
    "}"
    ".btn-primary:hover { "
    "    background: linear-gradient(135deg, #5a6fd8 0%, #6a4190 100%);"
    "}"
    ".btn-danger { "
    "    background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);"
    "    color: white; "
    "}"
    ".btn-danger:hover { "
    "    background: linear-gradient(135deg, #ee7deb 0%, #e74c5c 100%);"
    "}"
    ".info-text { "
    "    text-align: center; "
    "    color: #666; "
    "    font-size: 14px; "
    "    margin-top: 20px; "
    "}"
    "</style>"
    "</head>"
    "<body>"
    "<div class='container'>"
    "    <h2>🔧 Configuración WiFi</h2>"
    "    <form action='/save' method='post'>"
    "        <div class='form-group'>"
    "            <label for='ssid'>📶 Nombre de Red (SSID):</label>"
    "            <input type='text' id='ssid' name='ssid' placeholder='Ingresa el SSID de tu WiFi' required>"
    "        </div>"
    "        <div class='form-group'>"
    "            <label for='password'>🔑 Contraseña:</label>"
    "            <input type='password' id='password' name='password' placeholder='Contraseña de tu WiFi'>"
    "        </div>"
    "        <div class='form-group'>"
    "            <label for='retries'>🔄 Reintentos de Conexión (1-20):</label>"
    "            <input type='number' id='retries' name='retries' value='5' min='1' max='20' required>"
    "        </div>"
    "        <div class='form-group'>"
    "            <label for='delay'>⏱️ Delay entre Reintentos (ms):</label>"
    "            <input type='number' id='delay' name='delay' value='1000' min='100' max='10000' required>"
    "        </div>"
    "        <div class='checkbox-group'>"
    "            <input type='checkbox' id='save_creds' name='save_creds' checked>"
    "            <label for='save_creds'>💾 Guardar credenciales en memoria</label>"
    "        </div>"
    "        <button type='submit' class='btn btn-primary'>💾 Guardar Configuración</button>"
    "    </form>"
    "    <form action='/reset' method='post'>"
    "        <button type='submit' class='btn btn-danger'>🗑️ Resetear Credenciales</button>"
    "    </form>"
    "    <p class='info-text'>Después de guardar, el dispositivo se reiniciará automáticamente.</p>"
    "</div>"
    "</body>"
    "</html>";

#endif /* HTML_FORMS_H */