#ifndef HTML_RESPONSES_H
#define HTML_RESPONSES_H

const char* HTML_SAVE_SUCCESS = 
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "<title>Configuración Guardada</title>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<meta http-equiv='refresh' content='3;url=/'>"
    "<style>"
    "body { "
    "    font-family: Arial, sans-serif; "
    "    margin: 0; "
    "    padding: 20px; "
    "    background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);"
    "    min-height: 100vh;"
    "    display: flex;"
    "    justify-content: center;"
    "    align-items: center;"
    "    text-align: center;"
    "}"
    ".container { "
    "    background: white; "
    "    padding: 40px; "
    "    border-radius: 15px; "
    "    box-shadow: 0 10px 30px rgba(0,0,0,0.2);"
    "    max-width: 400px;"
    "}"
    "h2 { "
    "    color: #27ae60; "
    "    margin-bottom: 20px;"
    "}"
    "p { "
    "    color: #666; "
    "    font-size: 16px; "
    "    line-height: 1.5;"
    "}"
    ".loader { "
    "    border: 5px solid #f3f3f3; "
    "    border-top: 5px solid #27ae60; "
    "    border-radius: 50%; "
    "    width: 50px; "
    "    height: 50px; "
    "    animation: spin 1s linear infinite; "
    "    margin: 20px auto; "
    "}"
    "@keyframes spin { "
    "    0% { transform: rotate(0deg); } "
    "    100% { transform: rotate(360deg); } "
    "}"
    "</style>"
    "</head>"
    "<body>"
    "<div class='container'>"
    "    <h2>✅ Configuración Guardada</h2>"
    "    <div class='loader'></div>"
    "    <p>La configuración ha sido guardada exitosamente.</p>"
    "    <p>El dispositivo se reiniciará en 3 segundos...</p>"
    "</div>"
    "</body>"
    "</html>";

const char* HTML_RESET_SUCCESS = 
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "<title>Credenciales Reseteadas</title>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<meta http-equiv='refresh' content='3;url=/'>"
    "<style>"
    "body { "
    "    font-family: Arial, sans-serif; "
    "    margin: 0; "
    "    padding: 20px; "
    "    background: linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%);"
    "    min-height: 100vh;"
    "    display: flex;"
    "    justify-content: center;"
    "    align-items: center;"
    "    text-align: center;"
    "}"
    ".container { "
    "    background: white; "
    "    padding: 40px; "
    "    border-radius: 15px; "
    "    box-shadow: 0 10px 30px rgba(0,0,0,0.2);"
    "    max-width: 400px;"
    "}"
    "h2 { "
    "    color: #e74c3c; "
    "    margin-bottom: 20px;"
    "}"
    "p { "
    "    color: #666; "
    "    font-size: 16px; "
    "    line-height: 1.5;"
    "}"
    ".loader { "
    "    border: 5px solid #f3f3f3; "
    "    border-top: 5px solid #e74c3c; "
    "    border-radius: 50%; "
    "    width: 50px; "
    "    height: 50px; "
    "    animation: spin 1s linear infinite; "
    "    margin: 20px auto; "
    "}"
    "@keyframes spin { "
    "    0% { transform: rotate(0deg); } "
    "    100% { transform: rotate(360deg); } "
    "}"
    "</style>"
    "</head>"
    "<body>"
    "<div class='container'>"
    "    <h2>🗑️ Credenciales Reseteadas</h2>"
    "    <div class='loader'></div>"
    "    <p>Las credenciales WiFi han sido eliminadas.</p>"
    "    <p>El dispositivo se reiniciará en 3 segundos...</p>"
    "</div>"
    "</body>"
    "</html>";

const char* HTML_ERROR_PAGE = 
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "<title>Error</title>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<style>"
    "body { "
    "    font-family: Arial, sans-serif; "
    "    margin: 0; "
    "    padding: 20px; "
    "    background: linear-gradient(135deg, #ff6b6b 0%, #feca57 100%);"
    "    min-height: 100vh;"
    "    display: flex;"
    "    justify-content: center;"
    "    align-items: center;"
    "    text-align: center;"
    "}"
    ".container { "
    "    background: white; "
    "    padding: 40px; "
    "    border-radius: 15px; "
    "    box-shadow: 0 10px 30px rgba(0,0,0,0.2);"
    "    max-width: 400px;"
    "}"
    "h2 { "
    "    color: #e74c3c; "
    "    margin-bottom: 20px;"
    "}"
    "p { "
    "    color: #666; "
    "    font-size: 16px; "
    "    line-height: 1.5;"
    "}"
    ".btn { "
    "    display: inline-block; "
    "    padding: 12px 24px; "
    "    background: #3498db; "
    "    color: white; "
    "    text-decoration: none; "
    "    border-radius: 8px; "
    "    margin-top: 20px; "
    "    font-weight: bold; "
    "}"
    "</style>"
    "</head>"
    "<body>"
    "<div class='container'>"
    "    <h2>❌ Error</h2>"
    "    <p>Ha ocurrido un error inesperado.</p>"
    "    <a href='/' class='btn'>Volver al Inicio</a>"
    "</div>"
    "</body>"
    "</html>";

#endif /* HTML_RESPONSES_H */